---
- name: Add Apt update notifier metrics
  ansible.builtin.copy:
    src: apt-monitoring/apt-metrics.sh
    dest: /usr/share/
    owner: root
    group: root
    mode: "0755"
  tags:
    - monitoring
    - node_exporter

- name: Add Apt prometheus invoke hook
  ansible.builtin.copy:
    src: apt-monitoring/60prometheus-metrics
    dest: /etc/apt/apt.conf.d/
    owner: root
    group: root
    mode: "0644"
  tags:
    - monitoring
    - node_exporter

- name: Ensures Prometheus text file collector exists
  ansible.builtin.file:
    path: /var/lib/node_exporter/textfile_collector
    mode: "0755"
    state: directory
  tags:
    - monitoring
    - node_exporter
