---
- name: Use less swap if possible
  ansible.posix.sysctl:
    name: vm.swappiness
    value: '5'
    state: present

- name: Create directory for custom systemd settings
  ansible.builtin.file:
    path: "/etc/systemd/system.conf.d"
    state: directory
    owner: root
    group: root
    mode: "0750"

- name: Increase systems open file limits
  ansible.builtin.template:
    src: systemd/10-filelimit.conf.j2
    dest: "/etc/systemd/system.conf.d/10-filelimit.conf"
    mode: "0640"
    owner: root
    group: root
  tags:
    - system

- name: Set timezone to Europe/Berlin
  community.general.timezone:
    name: "{{ timezone }}"
  tags:
    - system

- name: Configure local lookups in /etc/hosts
  ansible.builtin.template:
    src: hosts.j2
    dest: "/etc/hosts"
    mode: "0644"
    owner: root
    group: root
  tags:
    - system

- name: Configure DNS
  ansible.builtin.template:
    src: systemd/resolved.conf.j2
    dest: /etc/systemd/resolved.conf
    mode: "0644"
    owner: root
    group: root
  notify:
    - Restart systemd-resolved
  tags:
    - system

- name: Installing generic build dependencies
  ansible.builtin.apt:
    install-recommends: false
    name:
      - bzip2
      - curl
      - git
      - make
      - ripgrep
      - shellcheck
      - tree
      - xz-utils
  tags:
    - build-dependencies

- name: Install required system packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: true

- name: "Create CICD group"
  ansible.builtin.group:
    name: "{{ cicd_group }}"
    state: present
  tags: [ 'cicd' ]

- name: "Create CICD user"
  ansible.builtin.user:
    name: "{{ cicd_user }}"
    shell: /bin/bash
    groups: "{{ cicd_group }}"
    state: present
  tags: [ 'cicd' ]
