---
- name: Create directory for custom systemd settings
  ansible.builtin.file:
    path: "/etc/systemd/system.conf.d"
    state: directory
    owner: root
    group: root
    mode: "0750"

- name: Increase systems open file limits
  ansible.builtin.template:
    src: systemd/10-filelimit.conf.j2
    dest: "/etc/systemd/system.conf.d/10-filelimit.conf"
    mode: "0640"
    owner: root
    group: root
  tags:
    - system

- name: Set timezone to Europe/Berlin
  community.general.timezone:
    name: "{{ timezone }}"
  tags:
    - system

- name: Configure local lookups in /etc/hosts
  ansible.builtin.template:
    src: hosts.j2
    dest: "/etc/hosts"
    mode: "0644"
    owner: root
    group: root
  tags:
    - system
