---
- name: Create directory for custom systemd settings
  ansible.builtin.file:
    path: "/etc/systemd/system.conf.d"
    state: directory
    owner: root
    group: root
    mode: "0750"

- name: Increase systems open file limits
  ansible.builtin.template:
    src: systemd/10-filelimit.conf.j2
    dest: "/etc/systemd/system.conf.d/10-filelimit.conf"
    mode: "0640"
    owner: root
    group: root

- name: Set timezone to Europe/Berlin
  timezone:
    name: "{{ timezone }}"
