---
- name: Installing OpenJDK {{ openjdk_version }}
  ansible.builtin.apt:
    name: "openjdk-{{ openjdk_version }}-jdk-headless={{ openjdk_pkg_version }}"
    state: present
    install_recommends: false
  tags:
    - java

- name: Set java version to OpenJDK {{ openjdk_version }}
  community.general.alternatives:
    name: java
    path: "/usr/lib/jvm/java-{{ openjdk_version }}-openjdk-amd64/bin/java"
  tags:
    - java

- name: Download and install Maven
  ansible.builtin.get_url:
    url: '{{ openjdk_maven_url }}'
    dest: /tmp/maven.tar.gz
    mode: "0440"
    checksum: 'sha512:{{ openjdk_maven_checksum_url }}'
  register: download_result
  tags:
    - maven

- name: Create Maven directory
  ansible.builtin.file:
    path: /opt/maven
    state: directory
    mode: "0755"
  tags:
    - maven

- name: Extract and install Maven
  ansible.builtin.unarchive:
    src: /tmp/maven.tar.gz
    dest: /opt/maven
    remote_src: true
    owner: root
    group: root
    extra_opts: [--strip-components=1]
  when: download_result.state == 'file'
  tags:
    - maven

- name: Set global environment variables for Java
  ansible.builtin.template:
    src: 20-java.sh
    dest: /etc/profile.d
    owner: root
    group: root
    mode: "0644"
