---
- name: Add Trivy key to a keyring file
  ansible.builtin.apt_key:
    url: "{{ trivy_key_url }}"
    keyring: "{{ trivy_key_ring_file }}"
  tags:
    - trivy
    - repository

- name: Install Trivy APT repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ trivy_key_ring_file }}] {{ trivy_repo_url }} {{ ansible_distribution_release }} main"
    state: present
    update_cache: true
  tags:
    - trivy
    - repository

- name: Install Trivy OCI security scanner
  ansible.builtin.apt:
    name:
      - trivy
  tags:
    - trivy

- name: Install syft generating SBOMs for container images
  ansible.builtin.command:
    cmd: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
    creates: /usr/local/bin/syft
  tags:
    - syft
