---
- name: Add Trivy key to a keyring file
  ansible.builtin.apt_key:
    url: "{{ trivy_key_url }}"
    keyring: "{{ trivy_key_ring_file }}"
  tags:
    - trivy
    - repository

- name: Install Trivy APT repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ trivy_key_ring_file }}] {{ trivy_repo_url }} {{ ansible_distribution_release }} main"
    state: present
    update_cache: true
  tags:
    - trivy
    - repository

- name: Install Trivy OCI security scanner
  ansible.builtin.apt:
    name:
      - trivy
  tags:
    - trivy

- name: Extract and install syft generating SBOMs for container images
  ansible.builtin.unarchive:
    src: "{{ syft_url }}"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: "0755"
    remote_src: true
  tags:
    - syft

- name: Extract and install SonarScanner CLI
  ansible.builtin.unarchive:
    src: "{{ sonar_scanner_cli_url }}"
    dest: /opt
    owner: "{{ cicd_user }}"
    group: "{{ cicd_group }}"
    remote_src: true
  tags:
    - sonar-scanner

- name: Create a symbolic link Sonar Scanner CLI
  ansible.builtin.file:
    src: /opt/sonar-scanner-{{ sonar_scanner_cli_version }}-{{ sonar_scanner_cli_os }}/bin/sonar-scanner
    dest: /usr/local/bin/sonar-scanner
    owner: "{{ cicd_user }}"
    group: "{{ cicd_group }}"
    state: link
  tags:
    - sonar-scanner

- name: Create a symbolic link Sonar Scanner CLI with debug
  ansible.builtin.file:
    src: /opt/sonar-scanner-{{ sonar_scanner_cli_version }}-{{ sonar_scanner_cli_os }}/bin/sonar-scanner-debug
    dest: /usr/local/bin/sonar-scanner-debug
    owner: "{{ cicd_user }}"
    group: "{{ cicd_group }}"
    state: link
  tags:
    - sonar-scanner

- name: Add Packer key to a keyring file
  ansible.builtin.apt_key:
    url: "{{ packer_key_url }}"
    keyring: "{{ packer_key_ring_file }}"
  tags:
    - packer
    - repository

- name: Install Packer APT repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ packer_key_ring_file }}] {{ packer_repo_url }} {{ ansible_distribution_release }} main"
    state: present
    update_cache: true
  tags:
    - packer
    - repository

- name: Install Packer
  ansible.builtin.apt:
    name:
      - packer
  tags:
    - packer
