---
- name: Include tasks to configure the operating system
  ansible.builtin.include_tasks: 01_system_settings.yaml

- name: Include tasks to setup OpenJDK
  ansible.builtin.include_tasks: 10_openjdk.yaml

- name: Include tasks to setup NodeJS
  ansible.builtin.include_tasks: 11_nodejs.yaml

- name: Include tasks to setup Docker container engine
  ansible.builtin.include_tasks: 20_docker.yaml

- name: Installing build tools
  ansible.builtin.apt:
    name:
      - bzip2
      - git
      - make
      - ripgrep
      - tree
      - xz-utils

- name: Include tasks to setup CircleCI runner
  ansible.builtin.include_tasks: 50_circleci.yaml
