---
- name: "Install CircleCI runner dependencies"
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - debian-archive-keyring
      - gpg
      - coreutils
      - curl
    state: present
  tags:
    - circleci-runner
    - dependencies

- name: "Add CircleCI key to a keyring file"
  ansible.builtin.apt_key:
    url: "{{ repository_key_url }}"
    keyring: "{{ repository_keyring_file }}"
  tags:
    - circleci-runner
    - repository

- name: "Install CircleCI repository"
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ repository_keyring_file }}] {{ repository_url }} any main"
    state: present
    update_cache: true
  tags:
    - circleci-runner
    - repository

- name: "Install CircleCI runner dependencies"
  ansible.builtin.apt:
    pkg:
      - circleci-runner

- name: "Configure CircleCI runner"
  ansible.builtin.template:
    src: circleci-runner-config.yaml.j2
    dest: "{{ circleci_config_path }}"
    mode: 0640
    owner: circleci

- name: "Enable and start circleci-runner systemd unit"
  ansible.builtin.service:
    name: circleci-runner.service
    state: started
    enabled: true
