---
- name: Include tasks to configure the operating system
  ansible.builtin.include_tasks: 01_system_settings.yaml

- name: Include tasks to setup OpenJDK
  ansible.builtin.include_tasks: 10_openjdk.yaml

- name: Include tasks to setup NodeJS
  ansible.builtin.include_tasks: 11_nodejs.yaml

- name: Include tasks to setup Docker container engine
  ansible.builtin.include_tasks: 20_docker.yaml

- name: Include tasks to install the OpenNMS repository
  ansible.builtin.include_tasks: 30_opennms.yaml

- name: Installing build tools
  ansible.builtin.apt:
    install-recommends: false
    name:
      - bzip2
      - git
      - jicmp
      - jicmp6
      - jrrd2
      - make
      - r-base
      - ripgrep
      - "rrdtool={{ rrdtool_version }}"
      - tree
      - xz-utils
  tags:
    - build-dependencies

- name: Installing Debian packaging tools
  ansible.builtin.apt:
    install-recommends: false
    name:
      - debhelper
      - devscripts
  tags:
    - build-dependencies
    - debian-packages

- name: Include tasks to setup CircleCI runner
  ansible.builtin.include_tasks: 50_circleci.yaml
