---
- name: Install GitHub Actions Runner service unit
  ansible.builtin.template:
    src: systemd/actions.runner.service.j2
    dest: /etc/systemd/system/actions.runner.service
    mode: "0664"
    owner: root
    group: root
  notify:
    - Restart actions-runner
  tags:
    - system
    - github-actions-runner
