---
- name: Install PostgreSQL build environment
  ansible.builtin.apt:
    name:
      - postgresql-14
      - postgresql-server-dev-14
  tags:
    - iplike

- name: Disable PostgreSQL server
  ansible.builtin.service:
    name: postgresql
    state: stopped
    enabled: false
