---
timezone: Europe/Berlin
# OpenJDK is a required for every component OpenNMS is running on and should be the same JDK version
system_filelimit: 1048576
system_arch: amd64
system_os: linux

dns:
  primary: 1.1.1.1
  secondary: 8.8.8.8

cicd_user: cicd
cicd_group: cicd
cicd_home: /home/{{ cicd_user }}
