---
- name: Add Docker repository key to a keyring file
  ansible.builtin.apt_key:
    url: "{{ docker_repo_key_url }}"
    keyring: "{{ docker_repo_keyring_file }}"
  tags:
    - docker
    - repository

- name: Install Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ docker_os_arch }} signed-by={{ docker_repo_keyring_file }}] {{ docker_repo_url }} {{ docker_os_version_codename }} {{ docker_release }}"
    state: present
    update_cache: true
  tags:
    - docker
    - repository

- name: Install Docker engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
  tags:
    - docker

- name: Add cicd user to group docker
  ansible.builtin.user:
    name: "{{ cicd_user }}"
    groups: docker
    append: true
  tags:
    - docker

- name: Add Trivy key to a keyring file
  ansible.builtin.apt_key:
    url: "{{ trivy_key_url }}"
    keyring: "{{ trivy_key_ring_file }}"
  tags:
    - trivy
    - repository

- name: Install Trivy APT repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by={{ trivy_key_ring_file }}] {{ trivy_repo_url }} {{ ansible_distribution_release }} main"
    state: present
    update_cache: true
  tags:
    - trivy
    - repository

- name: Install Trivy OCI security scanner
  ansible.builtin.apt:
    name:
      - trivy
  tags:
    - trivy

- name: Extract and install syft generating SBOMs for container images
  ansible.builtin.unarchive:
    src: "{{ syft_url }}"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: "0755"
    remote_src: true
  tags:
    - syft

- name: Dive for container image investigation
  ansible.builtin.apt:
    deb: "https://github.com/wagoodman/dive/releases/download/v{{ dive_version }}/dive_{{ dive_version }}_{{ system_os }}_{{ system_arch }}.deb"
  tags:
    - dive
