---
repository_url: https://packagecloud.io/circleci/runner/any
repository_key_url: https://packagecloud.io/circleci/runner/gpgkey
repository_keyring_file: /etc/apt/keyrings/circleci_runner-archive-keyring.gpg
circleci_config_path: /etc/circleci-runner/circleci-runner-config.yaml
api:
  auth_token: ""
runner:
  name: "{{ ansible_facts['hostname'] }}"
  working_directory: /data/circleci-runner/workdir
  cleanup_working_directory: "true"
logging:
  level: info
  format: text
  file: "-"
