---
- name: CI/CD-Runner
  hosts: cicd_runner
  become: true
  roles:
    - system-settings
    - docker-engine
    - prometheus.prometheus.node_exporter
    - monitoring
    - container-builder
    - java-builder
    - nodejs-builder
    - vm-builder
    - opennms

- name: Maven CDN
  hosts: mvn_cdn
  become: true
  roles:
    - docker-engine
    - mvn-cdn
