---
cicd_user: cicd
system_arch: amd64

docker_os_arch: "{{ system_arch }}"
docker_repo_url: https://download.docker.com/linux/ubuntu
docker_repo_key_url: https://download.docker.com/linux/ubuntu/gpg
docker_repo_keyring_file: /etc/apt/keyrings/docker.gpg
docker_os_version_codename: jammy
docker_release: stable
