---
name: bluebird-builder
run-name: Create Bluebird builder OCI for CICD infrastructure
on:
  workflow_dispatch:
  push:
    paths:
      - 'oci/bluebird-builder/**'

jobs:
  bluebird-oci-builder:
    runs-on: ubuntu-latest
    container:
      image: quay.io/bluebird/base-builder:0.0.4
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Create Dockerfile
        working-directory: oci/bluebird-builder
        run: make Dockerfile

      ## Any other branch just build locally, no docker push
      - name: Build container image
        if: github.ref != 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: ./oci/bluebird-builder
          # only single arch on branches, because of
          # ERROR: docker exporter does not currently support exporting manifest lists
          platforms: linux/amd64
          push: false
          load: true
          tags: bluebird-builder:b${{ github.run_number }}
      - name: Save image as artifact
        if: github.ref != 'refs/heads/main'
        working-directory: oci/bluebird-builder
        run: docker image save bluebird-builder:b${{ github.run_number }} -o build/bluebird-builder.oci
      - name: Persist OCI
        if: github.ref != 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: bluebird-builder-oci
          path: |
            oci/bluebird-builder/build/*.oci

      ## Main branch with push to registry
      - name: Login to Quay registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Build and push container image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: ./oci/bluebird-builder
          platforms: linux/amd64,linux/arm64
          push: true
          tags: quay.io/bluebird/bluebird-builder:0.3.3
